In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import nest

from scripts import visualizations, initializations, optimization, experiments, preprocessing, behaviour_analysis


              -- N E S T --
  Copyright (C) 2004 The NEST Initiative

 Version: 3.6.0
 Built: Sep 28 2023 11:53:34

 This program is provided AS IS and comes with
 NO WARRANTY. See the file LICENSE for details.

 Problems or suggestions?
   Visit https://www.nest-simulator.org

 Type 'nest.help()' to find out more about NEST.



In [2]:
df = pd.read_csv('/hpc/mzhu843/modelling/nest/DATA/raw/ezytrack/behaviour_LocationOutput.csv')
x_min, x_max, y_min, y_max = df['X'].min(), df['X'].max(), df['Y'].min(), df['Y'].max()
x_mid, y_mid = (x_min + x_max) / 2, (y_min + y_max) / 2

In [3]:
df['Quadrant'] = df.apply(behaviour_analysis.assign_quadrant, axis=1, args=(x_mid, y_mid))
# df.to_csv('/hpc/mzhu843/modelling/nest/DATA/processed/ezytrack/behaviour_LocationOutput_quadrants.csv', index = False)

In [4]:
total_frames = 17988
spikes = np.load("/hpc/mzhu843/modelling/nest/DATA/processed/spikes/experiment3_unfiltered_processed.npy")
print(np.where(spikes[0] == 1))
num_neurons = np.size(spikes, axis=0)
quadrants = df['Quadrant'].values
quadrants = np.vstack((quadrants, quadrants)).reshape(-1, order='F')[:total_frames]
print(quadrants)
spike_quadrant_counts = np.zeros((num_neurons, 4))

for i in range(num_neurons):
    spike_counts = np.zeros(4)
    for j in range(total_frames):
        if spikes[i][j] == 1:
            if quadrants[j] == 'Top Left':
                spike_counts[0] += 1
            elif quadrants[j] == 'Top Right':
                spike_counts[1] += 1
            elif quadrants[j] == "Bottom Left":
                spike_counts[2] += 1
            else:
                spike_counts[3] += 1
    spike_quadrant_counts[i] = spike_counts
print(spike_quadrant_counts)


(array([ 2541, 11645, 11944, 15543, 17624, 17656, 17674]),)
['Bottom Left' 'Bottom Left' 'Bottom Left' ... 'Top Right' 'Top Right'
 'Top Right']
[[ 0.  7.  0.  0.]
 [13. 18.  0.  0.]
 [46. 46. 24. 14.]
 [ 1.  1.  4.  0.]
 [ 6.  0.  1.  0.]
 [ 9.  0.  4.  0.]
 [ 6.  0. 23.  0.]
 [ 1.  0.  0.  0.]
 [20.  3.  3.  0.]
 [33. 36. 46. 39.]
 [13.  8. 24. 10.]
 [ 2.  0. 15.  0.]
 [ 2. 50.  0. 35.]
 [22.  2. 64.  7.]
 [ 0.  1.  1.  9.]
 [ 1. 17.  0.  0.]
 [15. 10.  3.  0.]
 [11. 36. 19. 21.]
 [ 0. 17.  1. 11.]
 [ 6.  0. 31.  0.]
 [ 1. 23.  2. 20.]
 [42. 14. 62. 24.]
 [79. 27. 60. 46.]
 [23. 14. 18.  1.]
 [42. 46. 43. 25.]
 [16.  7. 40. 29.]
 [11.  0. 21.  0.]
 [ 9.  0.  4.  0.]
 [ 2.  3. 17. 16.]
 [39.  6.  9.  0.]
 [80. 22.  2.  0.]
 [ 8.  4.  6. 19.]
 [ 3.  0.  4.  0.]
 [ 4.  8. 12. 12.]
 [12.  0.  2.  2.]
 [ 1. 10.  0.  0.]
 [ 1.  4.  0.  0.]
 [70. 24. 76. 34.]
 [ 0.  1.  0. 14.]
 [ 9. 10. 30. 13.]
 [24.  4. 54. 24.]
 [ 0.  0.  1.  0.]
 [37. 11. 87. 13.]
 [19.  3. 21.  8.]
 [ 0. 11.  3.  9.]
