In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/hpc/mzhu843/modelling/nest/DATA/raw/experiment3_unfiltered_raw.csv')
del df[df. columns[0]]

In [3]:
np_array = df.values

In [4]:

# Assuming 'arr' is your NumPy array
first_row = np_array[6, :]

# Get indices of non-zero elements in the first row
non_zero_indices = np.nonzero(first_row)[0]

# Create a dictionary from indices and their corresponding values
non_zero_dict = {index: first_row[index] for index in non_zero_indices}

# non_zero_dict now contains the indices and non-zero elements of the first row
print(non_zero_dict)

{2847: 0.0209985452431182, 5758: 0.0978037468177902, 5759: 0.1178443588140121, 5760: 0.103512535976469, 5761: 0.0856967167543881, 5762: 0.0658236830473801, 5763: 0.0011545269119464, 5794: 0.0101213631545433, 5795: 0.0499057080866523, 5796: 0.0472888120249572, 5797: 0.0424987255083383, 5798: 0.0100712587028897, 7028: 0.0292320441511957, 7029: 0.1253550494333391, 7030: 0.1338068260525739, 7031: 0.1406326762460043, 7032: 0.1453208219864157, 7033: 0.1474440289806252, 7034: 0.1467086666504115, 7035: 0.1429950559762784, 7036: 0.1363841986175062, 7037: 0.1271671974533399, 7038: 0.1158352539002641, 7039: 0.1030499916611577, 7040: 0.089595829083787, 7041: 0.0763180081034678, 7042: 0.0640514964121898, 7043: 0.0535471428643732, 7044: 0.0454020530579019, 7045: 0.0400010817237175, 7046: 0.0374755914412309, 7047: 0.0376842470448191, 7048: 0.0402187102878845, 7049: 0.044434825592183, 7050: 0.04950744058687, 7051: 0.0545046228909678, 7052: 0.058474971530188, 7053: 0.0605402204308225, 7054: 0.019945961

In [5]:
for i in range(np.size(np_array, axis=0)):
    counter = 0
    for j in range(np.size(np_array, axis=1)):
        if np_array[i][j] != 0 and counter == 0:
            np_array[i][j] = 1
            counter = 2
        elif np_array[i][j] != 0 and counter != 0:
            np_array[i][j] = 0
        elif np_array[i][j] == 0 and counter != 0:
            counter -= 1

<class 'numpy.ndarray'>


In [13]:
# Assuming 'arr' is your NumPy array
first_row = np_array[6, :]

# Get indices of non-zero elements in the first row
non_zero_indices = np.nonzero(first_row)[0]

# Create a dictionary from indices and their corresponding values
non_zero_dict = {index: first_row[index] for index in non_zero_indices}

# non_zero_dict now contains the indices and non-zero elements of the first row
print(non_zero_dict)



{2847: 1.0, 5758: 1.0, 5794: 1.0, 7028: 1.0, 7079: 1.0, 7109: 1.0, 7126: 1.0, 7166: 1.0, 7180: 1.0, 7794: 1.0, 7849: 1.0, 8161: 1.0, 8277: 1.0, 10717: 1.0, 10741: 1.0, 11043: 1.0, 12087: 1.0, 12106: 1.0, 12420: 1.0, 12458: 1.0, 12488: 1.0, 12820: 1.0, 12927: 1.0, 13272: 1.0, 16187: 1.0, 16408: 1.0, 16474: 1.0, 16501: 1.0, 16532: 1.0}
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [7]:
np.save('/hpc/mzhu843/modelling/nest/DATA/processed/experiment3_unfiltered_processed', np_array)
