In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import nest

from scripts import visualizations, initializations, optimization, experiments, preprocessing, behaviour_analysis


              -- N E S T --
  Copyright (C) 2004 The NEST Initiative

 Version: 3.6.0
 Built: Sep 28 2023 11:53:34

 This program is provided AS IS and comes with
 NO WARRANTY. See the file LICENSE for details.

 Problems or suggestions?
   Visit https://www.nest-simulator.org

 Type 'nest.help()' to find out more about NEST.



In [8]:
df = pd.read_csv('/hpc/mzhu843/modelling/nest/DATA/raw/ezytrack/behaviour_LocationOutput.csv')
x_min, x_max, y_min, y_max = df['X'].min(), df['X'].max(), df['Y'].min(), df['Y'].max()
x_mid, y_mid = (x_min + x_max) / 2, (y_min + y_max) / 2

73.0554732357844


In [3]:
df['Quadrant'] = df.apply(behaviour_analysis.assign_quadrant, axis=1, args=(x_mid, y_mid))
# df.to_csv('/hpc/mzhu843/modelling/nest/DATA/processed/ezytrack/behaviour_LocationOutput_quadrants.csv', index = False)

In [7]:
total_frames = 9017
spikes = np.load("/hpc/mzhu843/modelling/nest/DATA/processed/spikes/experiment3_unfiltered_processed.npy")
num_neurons = np.size(spikes, axis=0)
quadrants = df['Quadrant'].values
spike_quadrant_counts = np.zeros((num_neurons, 4))

for i in range(num_neurons):
    spike_counts = np.zeros(4)
    for j in range(total_frames):
        if spikes[i][j] != 0:
            if quadrants[j] == 'Top Left':
                spike_counts[0] += 1
            elif quadrants[j] == 'Top Right':
                spike_counts[1] += 1
            elif quadrants[j] == "Bottom Left":
                spike_counts[2] += 1
            else:
                spike_counts[3] += 1
    spike_quadrant_counts[i] = spike_counts
print(spike_quadrant_counts)


[[ 1.  0.  0.  0.]
 [ 7.  7.  8.  4.]
 [20. 21. 27. 18.]
 [ 0.  0.  0.  0.]
 [ 2.  2.  0.  1.]
 [ 1.  3.  1.  2.]
 [ 2.  3.  3.  5.]
 [ 0.  0.  0.  0.]
 [ 4.  1.  2.  3.]
 [ 0.  0.  1.  0.]
 [ 9. 11. 11.  6.]
 [ 0.  0.  0.  0.]
 [19. 15. 11.  7.]
 [10. 11.  9. 16.]
 [ 0.  0.  1.  0.]
 [ 3.  6.  4.  1.]
 [ 4.  2.  7.  3.]
 [26. 16. 12. 29.]
 [ 5.  6.  4.  2.]
 [ 8.  3.  9.  6.]
 [13.  8. 12. 13.]
 [ 8. 14. 16. 15.]
 [51. 44. 40. 46.]
 [14. 13. 16. 11.]
 [ 8. 13. 19.  7.]
 [18. 18. 22. 13.]
 [ 6.  4.  4.  5.]
 [ 0.  1.  0.  0.]
 [ 7.  5.  8.  9.]
 [ 4.  9. 10.  4.]
 [14. 12. 16. 13.]
 [ 7.  5.  8.  8.]
 [ 0.  2.  3.  1.]
 [ 3. 10. 13.  9.]
 [ 1.  1.  2.  0.]
 [ 3.  2.  1.  0.]
 [ 0.  0.  0.  0.]
 [15. 16. 19. 22.]
 [ 3.  1.  1.  1.]
 [ 8. 13. 12. 10.]
 [11.  9. 18. 12.]
 [ 0.  0.  0.  0.]
 [27. 18. 21. 17.]
 [ 9.  5.  7.  3.]
 [ 4.  2.  1.  3.]
 [ 0.  0.  0.  0.]
 [18. 13. 15. 11.]
 [ 4.  1.  2.  0.]
 [ 0.  3.  2.  3.]
 [ 1.  0.  0.  1.]
 [ 8.  2. 10.  3.]
 [20. 11. 16. 18.]
 [ 0.  1.  0